### ISSUE TITLE
RFC clarification and separation of concerns about the different objects/abstractions

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-resources#2]
@fenekku: 
> What is the difference between the
a) api.py Record,
b) the controller.py's RecordController and
c) the resources/record.py's RecordResource ?
I mean Record abstracts DB+ES record and adds a PID to it and RecordResource plays the role of the Flask-RESTful equivalent resource... but then what does the controller do? Record already knows about DB, ES... Like in the frontend, duplication of exact names is an indicator for me that we haven't settled on the responsibilities and their location.

**Comment by fenekku** [comment]
Since multiple people have now worked on this. I think it's clearer. Closing.
